sonar.projectKey=CloudSherpa-Intelligence
sonar.projectName=CloudSherpa Intelligence

sonar.sources=.
sonar.exclusions=src/tests/**, **/venv/**, **/.venv/**
sonar.tests=src/tests

sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=src/coverage.xml
