spring.application.name=normalization-service

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

# CloudSherpa consumers live inside consumer groups. It can be done where a consumer exists outside of
# an consumer group, but that requires careful manual config and management. If the group does not exist
# on the cluster, kafka creates the group.
spring.kafka.consumer.group-id=normalization-group

# If no offset exists, where should the consumer start reading
# Earliest starts from the beginning of the topic, no messages missed
spring.kafka.consumer.auto-offset=earliest

# Kafka message in bytes -> Java String 
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka message -> Avro Object according to schema
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer

# Tells kafka deserialize event into generated CloudUsageEvent object and other objects in future. 
spring.kafka.consumer.properties.specific.avro.reader=true

# Where schemas live (consumer requests schema from schema registry)
spring.kafka.properties.schema.registry.url=${SCHEMA_REGISTRY_URL:http://localhost:8081}

app.kafka.topics.cloud-usage=${CLOUD_USAGE_TOPIC:cloud.usage.v1}
