mode=dev
logging.level.org.springframework.security=DEBUG

# GCP dev properties
dev.gcp.billing_dev=${DEV_GCP_BILLING_DEV}
dev.gcp.project_id=${DEV_GCP_PROJECT_ID}
dev.gcp.dataset_id=${DEV_GCP_DATASET_ID}
dev.gcp.billing_account_id=${DEV_GCP_BILLING_ACCOUNT_ID}
dev.gcp.service_account_json_path=${DEV_GCP_SERVICE_ACCOUNT_JSON_PATH}