spring.application.name=ingestion
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:sherpadb}
spring.datasource.username=${POSTGRES_USER:cloudsherpa}
spring.datasource.password=${POSTGRES_PASSWORD:mock_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.swagger-ui.path=/swagger-ui.html
# Enable JobRunr background workers
org.jobrunr.background-job-server.enabled=true
org.jobrunr.background-job-server.worker-count=8
# Enable the JobRunr dashboard
org.jobrunr.dashboard.enabled=false
# Retry failed jobs 3 times by default
org.jobrunr.jobs.default-number-of-retries=3
sherpa.billing.aws.cur.tmp-dir=/tmp/sherpa/aws/cur
dev.gcp.billing_dev=${DEV_GCP_BILLING_DEV}
dev.gcp.project_id=${DEV_GCP_PROJECT_ID}
dev.gcp.dataset_id=${DEV_GCP_DATASET_ID}
dev.gcp.billing_account_id=${DEV_GCP_BILLING_ACCOUNT_ID}
