spring.application.name=ingestion
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:sherpadb}
spring.datasource.username=${POSTGRES_USER:cloudsherpa}
spring.datasource.password=${POSTGRES_PASSWORD:mock_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.swagger-ui.path=/swagger-ui.html
# Enable JobRunr background workers
org.jobrunr.background-job-server.enabled=true
org.jobrunr.background-job-server.worker-count=8
# Enable the JobRunr dashboard
org.jobrunr.dashboard.enabled=true
# Retry failed jobs 3 times by default
org.jobrunr.jobs.default-number-of-retries=3
logging.level.org.jobrunr=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG
