spring.application.name=ingestion
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:sherpadb}
spring.datasource.username=${POSTGRES_USER:cloudsherpa}
spring.datasource.password=${POSTGRES_PASSWORD:mock_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.swagger-ui.path=/swagger-ui.html
# Enable JobRunr background workers
org.jobrunr.background-job-server.enabled=true
org.jobrunr.background-job-server.worker-count=8
# Enable the JobRunr dashboard
org.jobrunr.dashboard.enabled=false
# Retry failed jobs 3 times by default
org.jobrunr.jobs.default-number-of-retries=3
sherpa.billing.aws.cur.tmp-dir=/tmp/sherpa/aws/cur
sherpa.api-key=${API_KEY}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql=ERROR
logging.level.org.hibernate=ERROR