mode=prod
logging.level.org.springframework.security=WARN
dashboard-host:${DASHBOARD_HOST}
springdoc.swagger-ui.enabled=false
auth.cookie.secure=true
spring.task.scheduling.pool.size=4

# Disable hibernate logging
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql=ERROR
logging.level.org.hibernate=ERROR