spring.application.name=service
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:analytics}
spring.datasource.username=${POSTGRES_USER:cloudsherpa}
spring.datasource.password=${POSTGRES_PASSWORD:mock_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect