# Base config, specialized by dev and prod configs
spring.application.name=service
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:sherpadb}
spring.datasource.username=${POSTGRES_USER:cloudsherpa}
spring.datasource.password=${POSTGRES_PASSWORD:mock_pass}
auth.jwt.secret=${AUTH_JWT_SECRET:mock_secret_32_chars_long_value_123456}
auth.jwt.exp-minutes=${AUTH_JWT_EXP_MINUTES:60}
# Careful note, this only works if injected to String[] type, should be a comma seperated list
allowed_origins=${ALLOWED_ORIGINS:http://localhost:3000}
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger/swagger-ui.html
# springdoc.swagger-ui.operationsSorter=method
# Hibernate Multi-Tenancy Configuration
spring.jpa.properties.hibernate.multiTenancy=SCHEMA