import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/atoms/card";

const ColorSwatch = ({ shade, variable }: { shade: string; variable: string }) => {
  return (
    <div className="flex flex-col gap-2">
      <div
        className="h-16 w-full rounded-md border border-neutral-200 dark:border-neutral-800 shadow-sm"
        style={{ backgroundColor: `var(${variable})` }}
      />
      <div className="flex flex-col">
        <span className="text-sm font-medium text-foreground">{shade}</span>
        <span className="text-xs text-muted-foreground">{variable}</span>
      </div>
    </div>
  );
};

export default function ColorsPage() {
  const shades = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"];
  const charts = [
    { name: "Chart 1 (Teal)", light: "--color-chart-teal-light", dark: "--color-chart-teal-dark" },
    { name: "Chart 2 (Amber)", light: "--color-chart-amber-light", dark: "--color-chart-amber-dark" },
    { name: "Chart 3 (Violet)", light: "--color-chart-violet-light", dark: "--color-chart-violet-dark" },
    { name: "Chart 4 (Rose)", light: "--color-chart-rose-light", dark: "--color-chart-rose-dark" },
    { name: "Chart 5 (Sky)", light: "--color-chart-sky-light", dark: "--color-chart-sky-dark" },
  ];

  return (
    <div className="flex flex-col gap-8 pb-12">
      <div>
        <h1 className="text-4xl font-bold tracking-tight mb-2">Colours</h1>
        <p className="text-lg text-muted-foreground">
          The primary colour palettes and chart primitives generated by our Style Dictionary.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Primary (Brand)</CardTitle>
          <CardDescription>
            Our core brand identity colors, ranging from 50 (lightest) to 950 (darkest).
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 sm:grid-cols-4 md:grid-cols-11 gap-4">
            {shades.map((shade) => (
              <ColorSwatch key={`brand-${shade}`} shade={shade} variable={`--color-brand-${shade}`} />
            ))}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Neutral</CardTitle>
          <CardDescription>
            Grayscale values used for backgrounds, borders, text, and structural UI elements.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 sm:grid-cols-4 md:grid-cols-11 gap-4">
            {shades.map((shade) => (
              <ColorSwatch key={`neutral-${shade}`} shade={shade} variable={`--color-neutral-${shade}`} />
            ))}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Chart Primitives</CardTitle>
          <CardDescription>
            Specific color primitives optimized for data visualization in light and dark modes.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="flex flex-col gap-4 p-6 bg-white border rounded-xl">
              <h3 className="font-semibold text-neutral-950">Light Mode Primitives</h3>
              <div className="grid grid-cols-2 sm:grid-cols-5 gap-4">
                {charts.map((chart) => (
                  <ColorSwatch key={chart.light} shade={chart.name} variable={chart.light} />
                ))}
              </div>
            </div>
            <div className="flex flex-col gap-4 p-6 bg-neutral-950 border border-neutral-800 rounded-xl">
              <h3 className="font-semibold text-neutral-50">Dark Mode Primitives</h3>
              <div className="grid grid-cols-2 sm:grid-cols-5 gap-4">
                {charts.map((chart) => (
                  <ColorSwatch key={chart.dark} shade={chart.name} variable={chart.dark} />
                ))}
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
