import type { KPIConfigTableRow } from "@/features/dashboard/components/kpi/config/columns";

export const mockKpiConfigRows: KPIConfigTableRow[] = [
    {
        resourceName: "Production API Gateway",
        resourceId: "api-gw-prod-01",
        service: "API Gateway",
        provider: "AWS",
        connection: "Production AWS",
    },
    {
        resourceName: "Customer Database",
        resourceId: "rds-customer-prod",
        service: "RDS",
        provider: "AWS",
        connection: "Production AWS",
    },
    {
        resourceName: "Billing Worker Cluster",
        resourceId: "eks-billing-workers",
        service: "EKS",
        provider: "AWS",
        connection: "Production AWS",
    },
    {
        resourceName: "Analytics Storage Bucket",
        resourceId: "s3-analytics-events",
        service: "S3",
        provider: "AWS",
        connection: "Data AWS",
    },
    {
        resourceName: "Cloud Cost Export",
        resourceId: "bigquery-cost-export",
        service: "BigQuery",
        provider: "GCP",
        connection: "Finance GCP",
    },
    {
        resourceName: "Production Load Balancer",
        resourceId: "alb-prod-public",
        service: "Elastic Load Balancing",
        provider: "AWS",
        connection: "Production AWS",
    },
    {
        resourceName: "Order Processing Queue",
        resourceId: "sqs-order-processing",
        service: "SQS",
        provider: "AWS",
        connection: "Production AWS",
    },
    {
        resourceName: "Invoice Archive",
        resourceId: "s3-invoice-archive",
        service: "S3",
        provider: "AWS",
        connection: "Data AWS",
    },
    {
        resourceName: "Events Warehouse",
        resourceId: "redshift-events-prod",
        service: "Redshift",
        provider: "AWS",
        connection: "Data AWS",
    },
    {
        resourceName: "Realtime Metrics Stream",
        resourceId: "kinesis-metrics-stream",
        service: "Kinesis",
        provider: "AWS",
        connection: "Data AWS",
    },
    {
        resourceName: "Finance Reports Dataset",
        resourceId: "bq-finance-reports",
        service: "BigQuery",
        provider: "GCP",
        connection: "Finance GCP",
    },
    {
        resourceName: "Cost Anomaly Function",
        resourceId: "cloud-function-cost-anomaly",
        service: "Cloud Functions",
        provider: "GCP",
        connection: "Finance GCP",
    },
    {
        resourceName: "Budget Alerts Topic",
        resourceId: "pubsub-budget-alerts",
        service: "Pub/Sub",
        provider: "GCP",
        connection: "Finance GCP",
    },
    {
        resourceName: "Customer Cache",
        resourceId: "elasticache-customer-prod",
        service: "ElastiCache",
        provider: "AWS",
        connection: "Production AWS",
    },
    {
        resourceName: "Media Processing Jobs",
        resourceId: "batch-media-processing",
        service: "AWS Batch",
        provider: "AWS",
        connection: "Production AWS",
    },
    {
        resourceName: "Audit Log Bucket",
        resourceId: "s3-audit-logs",
        service: "S3",
        provider: "AWS",
        connection: "Data AWS",
    },
    {
        resourceName: "Dataflow Cost Pipeline",
        resourceId: "dataflow-cost-pipeline",
        service: "Dataflow",
        provider: "GCP",
        connection: "Finance GCP",
    },
    {
        resourceName: "Forecast Model Training",
        resourceId: "vertex-forecast-training",
        service: "Vertex AI",
        provider: "GCP",
        connection: "Finance GCP",
    },
    {
        resourceName: "Container Registry",
        resourceId: "ecr-cloudsherpa-services",
        service: "ECR",
        provider: "AWS",
        connection: "Production AWS",
    },
    {
        resourceName: "Daily ETL Orchestrator",
        resourceId: "stepfn-daily-etl",
        service: "Step Functions",
        provider: "AWS",
        connection: "Data AWS",
    },
];
