name: CloudSherpa Images Build

on:
    push:
        branches:
            feature/continous-deployment
        paths:
            - ".github/workflows/build.yml"

concurrency:
    group: ecr-${{ github.ref }}
    cancel-in-progress: true

jobs:
    cloudsherpa-build:
        permissions:
            id-token: write
        runs-on: ubuntu-latest

        strategy:
            matrix:
                include:
                    - name: dashboard
                      context: .
                      dockerfile: apps/dashboard/Dockerfile

                    - name: service
                      context: .
                      dockerfile: apps/service/Dockerfile

                    - name: ingestion
                      context: .
                      dockerfile: apps/ingestion/Dockerfile

        steps:
            - name: Checkout repo
              uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22 # Version 7
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@e004cdcd2873919dbd2e62aa51128bedb3181599 # Version 6.1.0
              with:
                role-to-assume: ${{ vars.AWS_ACTIONS_ROLE_ARN }}
                aws-region: eu-north-1
            
            - name: Login to Amazon ECR Private
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build and push image
              env:
                REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                REPOSITORY: cloudsherpa
                IMAGE_TAG: "${{ matrix.name }}:${{ github.sha }}"
              run: |
                docker build --file "${{ matrix.dockerfile }}" --tag $IMAGE_TAG ${{ matrix.context }} 
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG