name: Ingestion CI triggered on edit

on:
    pull_request:
        types:
            - edited
        paths:
          - apps/ingestion/**
          - .github/workflows/ingestion-ci.yml
          - .github/workflows/ingestion-ci-edit.yml

jobs:
    ingestion-validation-on-edit:
        if: github.event.changes.base != null && (github.event.pull_request.base.ref == 'dev' || github.event.pull_request.base.ref == 'main')
        uses: ./.github/workflows/ingestion-ci.yml
        secrets: inherit
