name: Ingestion CI

on:
    pull_request:
        types:
          - opened
          - synchronize
          - reopened
        branches:
            - dev
            - main
        paths:
          - apps/ingestion/**
          - .github/workflows/ingestion-ci.yml
jobs:
    ingestion-validation:
        uses: ./.github/workflows/spring-ci.yml
        with:
          application-path: apps/ingestion
          sonar-project-key: CloudSherpa-ingestion
          sonar-project-name: 'CloudSherpa Ingestion' 
        secrets: inherit