name: Miscellaneous CI

on:
    pull_request:
        branches:
            - main
            - dev
        paths:
            - ".github/workflows/**"
            - "persistence/sherpadb/sherpadb-schema.sql"
            - "docs/**"
            - "apps/dashboard/Dockerfile"
            - "apps/ingestion/Dockerfile"
            - "apps/service/Dockerfile"
jobs:
    miscellaneous-validation:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v5
        
            - name: SonarQube Scan
              uses: SonarSource/sonarqube-scan-action@v8
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}