name: Service CI triggered on edit

on:
    pull_request:
        types:
            - edited

jobs:
    service-validation-on-edit:
        if: github.event.changes.base != null && (github.event.pull_request.base.ref == 'dev' || github.event.pull_request.base.ref == 'main')
        uses: ./.github/workflows/service-ci.yml
        secrets: inherit
