name: Service CI

on:
    pull_request:
        types:
          - opened
          - synchronize
          - reopened
        branches:
            - dev
            - main
        paths:
          - apps/service/**
          - .github/workflows/service-ci.yml

    workflow_call:
        
jobs:
    service-validation:
        uses: ./.github/workflows/spring-ci.yml
        with:
          application-path: apps/service
          sonar-project-key: CloudSherpa-service
          sonar-project-name: 'CloudSherpa Service' 
        secrets: inherit
